sudo: required

language: python
python:
  - 2.7
  - 3.6

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x86
  - TARGET_ARCH=x64

matrix:
  include:
    - os: osx
      language: generic
  exclude:
    - os: osx
      language: python

cache:
  directories:
    - $HOME/.ccache

install: true
script: 
  - chmod -R 777 scripts
  - function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  - timeout 2400 /bin/bash scripts/start.sh
