#!/usr/bin/env bash

# This script is use to update the version of VTK used by VTKPythonPackage. It
# is run nightly by a system with push permissions to the
#
#   git@github.com:jcfr/VTKPythonPackage.git
#
# repository.

set -x -e

workdir=/tmp/

cd $workdir

if test ! -d VTKNightlyMaster; then
  git clone --branch nightly-master \
    https://github.com/kitware/VTK.git VTKNightlyMaster
fi
pushd VTKNightlyMaster/
git checkout nightly-master
git fetch
git reset --hard origin/nightly-master
VTK_SHA=$(git rev-parse --short HEAD)
popd

if test ! -d VTKPythonPackage; then
  git clone --branch master \
    git@github.com:jcfr/VTKPythonPackage.git VTKPythonPackage
fi
pushd VTKPythonPackage/
git checkout master
git fetch
git reset --hard origin/master
git config user.name 'Kitware Robot'
git config user.email 'kwrobot@kitware.com'
VTKPythonPackage_SHA=$(git rev-parse --short HEAD)
./scripts/update_python_version.py ../VTKNightlyMaster
git add -- CMakeLists.txt vtkVersion.py
git commit -m "VTK nightly version update

This commit updates:
  (1) SHA used in CMakeLists.txt to checkout VTK sources
          (kitware/VTK@${VTK_SHA})
  (2) VERSION variable set in vtkVersion.py

It was automatically generated by the script ``update_python_version.sh`` [1]

[1] https://github.com/jcfr/VTKPythonPackage/blob/${VTKPythonPackage_SHA}/scripts/update_python_version.py"
git push origin master
